version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
            - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - app-network
        env_file: ".env"

    db:
        image: mysql:5.7
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: guest_book
            MYSQL_USER: guest
            MYSQL_PASSWORD: guest_password
        ports:
            - "3306:3306"
        volumes:
        - db_data:/var/lib/mysql           
        networks:
        - app-network                            

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www
        depends_on:
            - app
        networks:
            - app-network
volumes:
  db_data:
    driver: local 
    
networks:
    app-network:
        driver: bridge
